version: "3.3"
services:
  backend:
    build: backend
    container_name: ytsync_backend
    restart: unless-stopped
    networks:
      - nginx
  frontend:
    build: frontend
    container_name: ytsync_frontend
    restart: unless-stopped
    networks:
      - nginx

networks:
  nginx:
    external:
      name: nginx_default
