version: "3.3"
services:
  backend:
    build: backend
    container_name: yt-sync-backend
    restart: unless-stopped
    ports:
      - '4567:4567'
    networks:
      - nginx
  frontend:
    build: frontend
    container_name: yt-sync-frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    networks:
      - nginx

networks:
  nginx:
    external:
      name: nginx_nginx
