name: Release
on:
  push:
    branches:
      - master
jobs:
  build-tag-release:
    name: Build, tag, and release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          changelog-path: CHANGELOG.md
          package-name: yt-sync
      - name: Login to GitHub Container Registry
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Frontend Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd frontend
          git submodule update --init
          docker build \
          -t "ghcr.io/${GITHUB_REPOSITORY}-frontend:${{ steps.release.outputs.tag_name }}" \
          -t "ghcr.io/${GITHUB_REPOSITORY}-frontend:latest" .
      - name: Build Backend Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd backend
          docker build \
          -t "ghcr.io/${GITHUB_REPOSITORY}-backend:${{ steps.release.outputs.tag_name }}" \
          -t "ghcr.io/${GITHUB_REPOSITORY}-backend:latest" .
      - name: Release Docker image to ghcr.io
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker push "ghcr.io/${GITHUB_REPOSITORY}-frontend:${{ steps.release.outputs.tag_name }}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}-frontend:latest"
          docker push "ghcr.io/${GITHUB_REPOSITORY}-backend:${{ steps.release.outputs.tag_name }}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}-backend:latest"
